### ISSUE TITLE
Error while migrating albums without artists name

### ISSUE THREAD

**Issue by arun-doss** [jonathanbell/spotify2ytmusic-migration-script#1]
I know it is strange but some of my albums had no artists name in it, which causes error the following update resolved it for me.

Maybe a check to find if the artists name is present could be helpful.

![image](https://github.com/jonathanbell/spotify2ytmusic-migration-script/assets/20159261/5fcfe58a-be59-4915-abde-662007d8ec6a)

**Comment by jonathanbell** [comment]
Fixed by #4
